name: DDG File Change Monitor

on:
  pull_request:
    branches: [ ddg-files-modified-action ]
    types: [ opened, synchronize ]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
          apps/desktop/native-messaging-test-runner/**
          apps/desktop/src/services/duckduckgo-message-handler.service.ts

    - name: Comment on PR if monitored files changed
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const changedFiles = `${{ steps.changed-files.outputs.all_changed_files }}`.split(' ');
          
          const message = `⚠️🦆 **DuckDuckGo Integration files have been modified in this PR:**
          
          ${changedFiles.map(file => `- \`${file}\``).join('\n')}
          
          Please run the DuckDuckGo native messaging test runner from this branch using these instructions (https://contributing.bitwarden.com/getting-started/clients/desktop/native-messaging-test-runner) and ensure it functions properly`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });
